#!/usr/bin/env bash

directories=(
    bin
    btop
    hypr
    nvim
    personal
    tmux
    wezterm
    zsh
)

for dir in "${directories[@]}"; do
    echo "Stowing $dir..."
    stow "$dir" -t "$HOME"
done

echo "Stowing finished"
