#!/usr/bin/env bash

directories=(
    bin
    btop
    hypr
    nvim
    personal
    tmux
    wezterm
    zsh
)

for dir in "${directories[@]}"; do
    echo "Unstowing $dir..."
    stow -D "$dir" -t "$HOME"
done

echo "Unstowing finished"
