---
- name: "Zsh | Checking for distribution config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: zsh_distribution_config

- name: "Zsh | Run tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: zsh_distribution_config.stat.exists

- name: "Zsh | Configure zsh"
  ansible.builtin.copy:
    src: zsh/*
    dest: "{{ ansible_user_dir }}/"
    mode: "0644"
    force: true

- name: "Zsh | Change shell to zsh"
  ansible.builtin.command:
    cmd: chsh -s $(which zsh)

- name: "Zsh | Check if oh-my-zsh exists"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: oh_my_stats

- name: "Zsh | Install oh-my-zsh"
  ansible.builtin.cmd:
    cmd: "curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer"
  when: not oh_my_stats.stat.exists
  become: true
