---
- name: "zsh | install zsh"
  ansible.builtin.package:
    name: "zsh"
    state: "present"
  become: true

- name: "zsh | check for existing oh-my-zsh"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: install

- name: "zsh | download oh-my-zsh"
  ansible.builtin.get_url:
    dest: /tmp/zsh-install.sh
    mode: "0755"
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  when: not install.stat.exists

- name: "zsh | install oh-my-zsh"
  ansible.builtin.shell: /tmp/zsh-install.sh
  when: not install.stat.exists

- name: "zsh | remove oh-my-zsh installer"
  ansible.builtin.file:
    path: /tmp/zsh-install.sh
    state: absent

- name: "zsh | remove oh-my-zsh default config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: "absent"
  loop:
    - ".zshrc"
    - ".zshrc.pre-oh-my-zsh"

- name: "zsh | symlink config"
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item }}"
    mode: "0644"
    state: "link"
  loop:
    - ".zshrc"
    - ".zprofile"

- name: "zsh | change shell to zsh"
  ansible.builtin.command:
    cmd: "chsh -s /bin/zsh {{ ansible_facts['env']['USER'] }}"
  become: true
