---
- name: "zsh | install zsh"
  ansible.builtin.package:
    name: "zsh"
    state: "present"
  become: true

- name: "zsh | symlink config"
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item }}"
    mode: "0644"
    state: "link"
  loop:
    - ".zshrc"
    - ".zprofile"

- name: "zsh | change shell to zsh"
  ansible.builtin.command:
    cmd: "chsh -s /bin/zsh {{ ansible_facts['env']['USER'] }}"
  become: true
