- name: "Git | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "Git | Set init.defaultBranch"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
    
- name: "Git | Set core.editor"
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim

- name: "Git | Set gpg.program"
  community.general.git_config:
    name: gpg.program
    scope: global
    value: "{{ ansible_user_dir }}/.local/bin/gpg"

- name: "Git | Set user.name"
  community.general.git_config:
    name: user.name
    scope: global
    value: calebgl

- name: "Git | Set user.email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true

