- name: "git | set init.defaultBranch"
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: "git | set core.editor"
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim

- name: "git | user.name"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: "git | user.email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ github_email }}"
  no_log: true

- name: "git | user.signinkey"
  community.general.git_config:
    name: user.signinkey
    scope: global
    value: "{{ ansible_user_dir }}/.ssh/id_d25519.pub"

- name: "git | commit.gpgsign"
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true

- name: "git | gpg.format"
  community.general.git_config:
    name: gpg.format
    scope: global
    value: ssh

- name: "git | set gpg.ssh.allowedSignersFile"
  community.general.git_config:
    name: gpg.ssh.allowedSignersFile
    scope: global
    value: "{{ ansible_user_dir }}/.ssh/allowed_signers"

- name: "git | config gitlab repos"
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.gitconfig"
    block: |
      [includeIf "hasconfig:remote.*.url:https://gitlab.com/**"]
      path = ~/.gitlab
      [includeIf "hasconfig:remote.*.url:git@gitlab.com:**"]
      path = ~/.gitlab
    state: present

- name: "git | set user.email for gitlab"
  community.general.git_config:
    name: user.email
    scope: file
    file: "{{ ansible_user_dir }}/.gitlab"
    value: "{{ gitlab_email }}"
  no_log: true
