---
- name: "Tmux | Checking for distribution config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: tmux_distribution_config

- name: "Tmux | Run tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: tmux_distribution_config.stat.exists

- name: "Tmux | Configure tmux"
  ansible.builtin.copy:
    src: tmux
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Tmux | Install tpm"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm"

- name: "Tmux | Ensure {{ ansible_user_dir }}/.local/bin directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: "0700"

- name: "Tmux | Configure tmux-sessionizer"
  ansible.builtin.copy:
    src: "tmux-sessionizer"
    dest: "{{ ansible_user_dir }}/.local/bin" 
    mode: "0711"
