---
- name: "Nvim | Uninstall apt nvim"
  ansible.builtin.apt:
    name: neovim
    state: absent
  become: true

- name: "Nvim | Clone latest version"
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: "{{ ansible_user_dir }}/.nvim"

- name: "Nvim | Install build dependencies"
  ansible.builtin.apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
    state: present
  become: true

- name: "Nvim | Install nvim"
  ansible.builtin.shell: |
    cd {{ ansible_user_dir }}/.nvim
    make CMAKE_BUILD_TYPE=RelWithDebInfo
    make install
    exit 0
  become: true
