---
- name: "nvim | install nvim"
  ansible.builtin.package:
    name: neovim
    state: present
  become: true

- name: "nvim | ensure ~/.config/nvim directory exists"
  ansible.builtin.file:
    mode: "0700"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "nvim | symlink config"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
