---
- name: "Nvim | Checking for distribution config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: nvim_distribution_config

- name: "Nvim | Run tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: nvim_distribution_config.stat.exists
